name: Security Pipeline

on:
  push:
  pull_request:

jobs:
  bandit_scan:
    name: Bandit Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit
        run: |
          mkdir -p resultados
          bandit -r . -f json -o resultados/bandit-default.json
      - name: Upload Bandit Results
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: resultados/bandit-default.json

  semgrep_scan:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          json: true
          output: resultados/semgrep-default.json
      - name: Upload Semgrep Results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: resultados/semgrep-default.json

  zap_scan:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10-dind
        options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Start Juice Shop container
        run: |
          docker network create zap-net
          docker run -d --name webapp --network zap-net -p 3000:3000 bkimminich/juice-shop
      - name: Run ZAP Scan
        run: |
          mkdir -p zap-report
          docker run --rm --network zap-net \
            -v ${{ github.workspace }}/zap-report:/zap/wrk:rw \
            zaproxy/zap-stable:latest \
            zap-baseline.py \
              -t http://webapp:3000 \
              -r zap-default.html \
              -J zap-result.json
      - name: Upload ZAP Results
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report