name: Security CI Pipeline

on:
  push:
  pull_request:

jobs:
  security-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Initializing security pipeline..."
          mkdir -p security-reports
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: security-reports

  build-secure:
    runs-on: ubuntu-latest
    needs: [security-setup]
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker build -t secure-todo-backend:${{ github.sha }} -f infrastructure/Dockerfile.backend.secure .
          docker build -t secure-todo-frontend:${{ github.sha }} -f infrastructure/Dockerfile.frontend.secure .
          docker save secure-todo-backend:${{ github.sha }} > backend-image.tar
          docker save secure-todo-frontend:${{ github.sha }} > frontend-image.tar
      - uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            backend-image.tar
            frontend-image.tar